config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :home_banners
  resources :marquees
  resources :patterns
  resources :notices
  resources :frases
  resources :users
  resources :products

  get 'producto/:id', to: 'products#showpub', as: 'producto'
  get 'catalogo', to: 'pages#store', as: 'store'
  get 'sobre-mi', to: 'pages#about', as: 'about_me'
  get 'contacto', to: 'pages#contact', as: 'contact'
  get 'galeria', to: 'pages#gallery', as: 'gallery'
  get 'trabajando', to: 'pages#working'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get 'forbidden', to: 'pages#forbidden'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/notice.rb
class Notice < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :desc
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: %i[ show edit update destroy ]
  before_action :require_user
  before_action :require_admin_user

  # GET /notices or /notices.json
  def index
    @notice = Notice.last
  end

  # GET /notices/1 or /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices or /notices.json
  def create
    @notice = Notice.new(notice_params)

    if @notice.save
      flash[:success] = 'Noticia creada con éxito'
      redirect_to @notice
    else
      flash[:danger] = "Hubo un error al crear la noticia. Errores: #{@notice.errors.full_messages}"
      render 'new'
    end
  end

  # PATCH/PUT /notices/1 or /notices/1.json
  def update

    if @notice.update(notice_params)
      flash[:success] = 'Noticia creada con éxito'
      redirect_to @notice
    else
      flash[:danger] = "Hubo un error al crear la noticia. Errores: #{@notice.errors.full_messages}"
      render 'new'
    end
  end

  # DELETE /notices/1 or /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: "Notice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notice_params
      params.require(:notice).permit(:title, :desc)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<div class="notice-form-container">
  <%if @notice.new_record?%>
    <h1>Nueva noticia</h1>
  <%else%>
    <h1>Actualizar noticia</h1>
  <%end%>
  <%= form_for(@notice, :html => {class: 'notice-form', role: 'form'}) do |form| %>

    <div class="field">
      <%= form.label 'Título' %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label 'Contenido' %>
      <%= form.text_area :desc, class:'notice-textarea' %>
    </div>

    <div class="actions">
      <%= form.submit(@notice.new_record? ? 'Crear' : 'Actualizar', class:'btn-primary')%>
    </div>
  <% end %>

  <%= link_to 'Volver', url_for(:back), class:'btn-primary', style:'width:75px;' %>
</div>

app/views/notices/edit.html.erb
<%= render 'form', notice: @notice %>

app/views/notices/index.html.erb
<div class="notices-container">
  <h1>Última noticia publicada :</h1>
  <%if @notice%>
  <div class="notice">
    <p><%=@notice.title%></p>
    <p><%=@notice.desc%></p>
    <%= link_to 'Actualizar', edit_notice_path(@notice), class:'notice-btn' %>
  </div>
  <%else%>
  <div class="notice">
    <p>No hay noticias</p>
  </div>
  <%end%>
  <%= link_to 'Crear nueva noticia', new_notice_path, class:'notice-btn' %>
  <%=link_to 'Volver', url_for(:back), class:'btn-danger'%>
</div>

app/views/notices/new.html.erb
<%= render 'form', notice: @notice %>

<%=link_to 'Volver', url_for(:back), class:'btn-danger'%>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notice.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @notice.desc %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%=link_to 'Volver', url_for(:back), class:'btn-danger'%>