config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :home_banners
  resources :marquees
  resources :patterns
  resources :notices
  resources :frases
  resources :users
  resources :products

  get 'producto/:id', to: 'products#showpub', as: 'producto'
  get 'catalogo', to: 'pages#store', as: 'store'
  get 'sobre-mi', to: 'pages#about', as: 'about_me'
  get 'contacto', to: 'pages#contact', as: 'contact'
  get 'galeria', to: 'pages#gallery', as: 'gallery'
  get 'trabajando', to: 'pages#working'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get 'forbidden', to: 'pages#forbidden'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {minimum:3, maximum:25}, uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:105}, uniqueness: {case_Sensitive: false}, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user
  before_action :require_admin_user

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="user-form-container">
  <% if @user.errors.any? && @user.new_record?%>
    <h1>Crear usuario</h1>
  <%else%>
    <h1>Editar usuario</h1>
  <%end%>
    <%= form_for(@user, :html => {class: 'form-user', role: 'form'}) do |f| %>
      <div class="form-group">
        <div class="control-label">
          <%= f.label :nombre %>
        </div>
        <div>
          <%= f.text_field :name, class: 'form-control', placeholder: 'User name', autofocus: true%>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label">
          <%= f.label :email %><br/>
        </div>
        <div>
          <%= f.email_field :email, class: 'form-control', placeholder: 'User email'%>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label">
          <%= f.label :contraseña%><br/>
        </div>
        <div>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Enter password'%>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit(@user.new_record? ? "Registrarse" : "Actualizar cuenta", class: 'btn btn-primary btn-lg submitbtn')%>
      </div>
    <%end%>

  <%= link_to 'Volver', url_for(:back), class: 'btn-danger' %>
</div>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="users-wrapper">
  <h1>Usuarios</h1>

  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Email</th>
        <th>Creación</th>
        <th>Rol</th>
        <th>Acciones</th>
      </tr>
    </thead>
  
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.strftime("%d/%m/%Y") %></td>
          <td>
            <%if user.admin?%>
              <p style="color: rgb(93, 117, 255); font-weight: bold;">Admin</p>
            <%else%>
              <p style="color: rgb(93, 117, 255); font-weight: bold;">Normal</p>
            <%end%>
          </td>
          <td>
            <%= link_to 'Ver', user, class:'btn-primary' %>
            <%= link_to 'Editar', edit_user_path(user), class:'btn-primary' %>
            <%= link_to 'Borrar', user, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Volver', url_for(:back), class: 'btn-danger', style:'margin-top:20px' %>
</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<%if @user.admin?%>
  <div class="admin-user-wrapper">
    <h2>Bienvenido, <%=@user.name%></h2>

    <div class="actions">
      <p>Acciones disponibles</p>

      <div class="list">
        <ul>
          <li>Usuarios: 
            <%=link_to 'Administrar', users_path, class:'btn-primary btn-sm'%>
            <%=link_to 'Editar', edit_user_path(@user), class: 'btn-alert btn-sm' %>
            <%=link_to 'Cerrar sesión', logout_path, method: :delete, class:'btn-danger btn-sm'%>
          </li>
          <li>Productos: 
            <%=link_to 'Administrar productos', products_path, class:'btn-alert btn-sm'%>
            <%=link_to 'Crear nuevo producto', new_product_path, class:'btn-primary btn-sm'%>

          </li>
          <li>Frases: 
            <%=link_to 'Crear nueva frase', new_frase_path, class:'btn-primary btn-sm'%>
          </li>
          <li>Noticias: 
            <%=link_to 'Crear nueva noticia', new_notice_path, class:'btn-primary btn-sm'%>
          </li>
          <li>Patrones: 
            <%=link_to 'Administrar patrones', patterns_path, class:'btn-alert btn-sm'%>
            <%=link_to 'Crear un nuevo patrón', new_pattern_path, class:'btn-primary btn-sm'%>
          </li>
          <li>Marquees:
            <%=link_to 'Marquee actual', marquees_path, class:'btn-primary btn-sm'%> 
            <%=link_to 'Crear nuevo marquee', new_marquee_path, class:'btn-primary btn-sm'%>
          </li>
          <li>Reseñas: 
            <%=link_to 'Crear nueva reseña', new_review_path, class:'btn-primary btn-sm'%>
          </li>

          <li>Home Banners: 
            <%=link_to 'Nuevo set', new_home_banner_path, class:'btn-primary btn-sm'%>
            <%=link_to 'Set actual', home_banners_path, class: 'btn-alert btn-sm'%>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <%= link_to 'Volver', url_for(:back), class: 'btn-danger', style:'margin-top:50px;display:inline-block' %>
<%else%>
  <div class="common-user-wrapper">
    <h2>Bienvenido, <%=@user.name%></h2>

    <div class="actions">
      <p>Acciones disponibles</p>
      <%=link_to 'Cerrar sesión', logout_path, method: :delete, class:'btn-primary'%>
      <%= link_to 'Editar usuario', edit_user_path(@user), class: 'btn-primary' %>
    </div>
    <%= link_to 'Volver', url_for(:back), class: 'btn-danger' %>
  </div>
<%end%>