config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :home_banners
  resources :marquees
  resources :patterns
  resources :notices
  resources :frases
  resources :users
  resources :products

  get 'producto/:id', to: 'products#showpub', as: 'producto'
  get 'catalogo', to: 'pages#store', as: 'store'
  get 'sobre-mi', to: 'pages#about', as: 'about_me'
  get 'contacto', to: 'pages#contact', as: 'contact'
  get 'galeria', to: 'pages#gallery', as: 'gallery'
  get 'trabajando', to: 'pages#working'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get 'forbidden', to: 'pages#forbidden'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/pattern.rb
class Pattern < ApplicationRecord
  serialize :images
  before_save :convert_images_to_a

  def convert_images_to_a
    self.images = self.images.split(',')
  end

  def formatted_images
    formatted_images = self.images.join(', ')
    formatted_images
  end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :set_pattern, only: %i[ show edit update destroy ]
  before_action :require_user, except: %i[index show]
  before_action :require_admin_user, except: %i[index show]

  # GET /patterns or /patterns.json
  def index
    @patterns = Pattern.paginate(page: params[:page], per_page: 4)

    @image_styles = 'width: 350px;'
  end

  # GET /patterns/1 or /patterns/1.json
  def show
    @image_styles = 'width: 500px;height:500px;object-fit:cover;'
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  # GET /patterns/1/edit
  def edit
  end

  # POST /patterns or /patterns.json
  def create
    @pattern = Pattern.new(pattern_params)

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to @pattern, notice: "Pattern was successfully created." }
        format.json { render :show, status: :created, location: @pattern }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patterns/1 or /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to @pattern, notice: "Pattern was successfully updated." }
        format.json { render :show, status: :ok, location: @pattern }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1 or /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url, notice: "Pattern was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pattern_params
      params.require(:pattern).permit(:name, :description, :images, :price)
    end
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/views/patterns/_form.html.erb
<div class="pattern-form-container">
  <%= form_with(model: pattern) do |form| %>

  <div class="field">
    <%= form.label 'Nombre' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label 'Descripción' %>
    <%= form.text_area :description %>
  </div>

  <div class="images-field">
    <%= form.label 'Imagenes' %>
    <%= form.text_area :images, value: @pattern.formatted_images %>
    <span class="form-helper">Siempre pegar primero la imagen principal y separar por comas si es más de una imagen</span>
  </div>

  <div class="field">
    <%= form.label 'Precio' %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit(@pattern.new_record? ? 'Crear patrón' : 'Actualizar patrón', class: 'btn-primary') %>
  </div>
  <% end %>
</div>

app/views/patterns/_slideshow.html.erb
<!-- Slider main container -->
<div data-controller="carousel" class="swiper-container" data-carousel-options-value='
  {
    "pagination": {"el": ".swiper-pagination", "dynamicBullets": "true"},
    "navigation": {"nextEl": ".swiper-button-next", "prevEl": ".swiper-button-prev"}
  }'>
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper">
    <!-- Slides -->
    <%images.each do |img|%>
      <div class="swiper-slide">
        <img src="<%=img%>" alt="image" style="<%=@image_styles%>">
      </div>
    <%end%>
  </div>

  <div class="swiper-pagination"></div>
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>

app/views/patterns/edit.html.erb
<h1 style="text-align:center;">Editar patrón</h1>

<%= render 'form', pattern: @pattern %>

<%=link_to 'Volver', url_for(:back), class:'btn-danger'%>

app/views/patterns/index.html.erb
<div class="pattern-container">
  <div class="patterns-banner">
    <h1>Patrones</h1>
  </div>

  <div class="patterns" style="margin-bottom:50px;">
    <%@patterns.each do |pattern|%>
      <div class="pattern">
        <div class="pattern-images">
          <%=render 'slideshow', images: pattern.images%>
        </div>
        <div class="pattern-text">
          <p class="name"><%=pattern.name%></p>
          <p class="price" style="font-style:italic;font-weight:600;">$ <%=pattern.price%></p>
          <div class="actions">
            <%if current_user.admin?%>
              <%=link_to 'Ver patrón', pattern_path(pattern), class: 'btn-primary'%>
              <%=link_to edit_pattern_path(pattern), class: 'btn-alert' do%>
                <i class="fa-solid fa-pencil"></i>
              <%end%>

              <%=link_to pattern_path(pattern), method: :delete, data: { confirm: 'Seguro?' }, class: 'btn-danger' do%>
                <i class="fa-solid fa-trash"></i>
              <%end%>
            <%else%>
              <%=link_to 'Ver patrón', pattern_path(pattern), class: 'btn-primary'%>
            <%end%>
          </div>
        </div>
      </div>
    <%end%>
  </div>

<%= will_paginate @patterns, :previous_label => 'Anterior', :next_label => 'Siguiente' %>

</div>
<%=render 'layouts/footer'%>

app/views/patterns/new.html.erb
<h1>New Pattern</h1>

<%= render 'form', pattern: @pattern %>

<%=link_to 'Volver', url_for(:back), class:'btn-danger'%>

app/views/patterns/show.html.erb
<div class="show-pattern-wrapper" style="margin-bottom:50px;">
  <div class="left">
    <div class="show-images">
      <%=render 'slideshow', images: @pattern.images%>
    </div>
    
  </div>

  <div class="right">
    <p class="name"><%=@pattern.name%></p>
    <p class="price">$ <%=@pattern.price%></p>
    <p class="description"><%=@pattern.description%></p>
    <button class="btn-primary">Comprar</button>
  </div>
</div>
<%=link_to 'Volver', url_for(:back), class:'btn-danger'%>

<%=render 'layouts/footer'%>