config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :home_banners
  resources :marquees
  resources :patterns
  resources :notices
  resources :frases
  resources :users
  resources :products

  get 'producto/:id', to: 'products#showpub', as: 'producto'
  get 'catalogo', to: 'pages#store', as: 'store'
  get 'sobre-mi', to: 'pages#about', as: 'about_me'
  get 'contacto', to: 'pages#contact', as: 'contact'
  get 'galeria', to: 'pages#gallery', as: 'gallery'
  get 'trabajando', to: 'pages#working'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get 'forbidden', to: 'pages#forbidden'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord 
  has_many :products
end

app/models/frase.rb
class Frase < ApplicationRecord
end

app/models/home_banner.rb
class HomeBanner < ApplicationRecord
  serialize :images
  before_save :convert_images_to_a

  def convert_images_to_a
    self.images = self.images.split(',')
  end

  def formatted_images
    formatted_images = self.images.join(', ')
    formatted_images
  end
end

app/models/marquee.rb
class Marquee < ApplicationRecord
end

app/models/notice.rb
class Notice < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :desc
end

app/models/pattern.rb
class Pattern < ApplicationRecord
  serialize :images
  before_save :convert_images_to_a

  def convert_images_to_a
    self.images = self.images.split(',')
  end

  def formatted_images
    formatted_images = self.images.join(', ')
    formatted_images
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include Filterable

  has_one_attached :image
  belongs_to :category

  scope :filter_by_category, -> (category) { 
    joins(:category).where('category.name' => category)
  }
end

app/models/review.rb
class Review < ApplicationRecord
  serialize :images
  before_save :convert_images_to_a

  def convert_images_to_a
    self.images = self.images.split(',')
  end

  def formatted_images
    formatted_images = self.images.join(', ')
    formatted_images
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {minimum:3, maximum:25}, uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:105}, uniqueness: {case_Sensitive: false}, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @store_preview = Product.last(8)
    @home_categories = Category.all
    @home_banner_big = HomeBanner.where(screen_type: 'pantalla_grande').last
    @home_banner_phone = HomeBanner.where(screen_type: 'Celular').last
  end

  def store
    @products = Product.filter(params.slice(:category)).paginate(page: params[:page], per_page: 21).order(price: order_by)
    @categories = Category.all
  end

  def about
    @frase = Frase.last
    @noticia = Notice.last
  end

  def contact
  end

  def working
  end

  def gallery
    @reviews = Review.all
  end

  def forbidden
  end

  private
  def order_by
    if params[:order] == 'Mayor a menor'
      :desc
    elsif params[:order] == 'Menor a mayor'
      :asc
    else
      :asc
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frases_helper.rb
module FrasesHelper
end

app/helpers/home_banners_helper.rb
module HomeBannersHelper
  def options_for_types
    [
      ['Celular', 'celular'],
      ['Pantalla grande', 'pantalla_grande']
    ]
  end
end

app/helpers/marquees_helper.rb
module MarqueesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def categories_for_select
    Category.all.collect { |c| [c.name, c.id] }
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer-content">
    <h4>Hidden Petal &copy; <%=Date.today.year%></h4>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
<div class="alert">
  <div class="flash-msg flash-<%=type%>">
    <p><%= msg %></p>
  </div>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar-header">
  <div class="navbar-menu-left">
    <%=image_tag 'logo.png', class: 'logo-image'%>
    <%=link_to 'Inicio' , root_path, class: {active: current_page?(root_path)}%>
      <%=link_to 'Galería' , gallery_path, class: {active: current_page?(gallery_path)}%>
        <%=link_to 'Contacto' , contact_path, class: {active: current_page?(contact_path)}%>
          <%=link_to 'Sobre mi' , about_me_path, class: {active: current_page?(about_me_path)}%>
            <%=link_to 'Catálogo' , store_path, class: {active: current_page?(store_path)}%>
              <%=link_to 'Patrones' , patterns_path, class: {active: current_page?(patterns_path)}%>
  </div>
  <div class="navbar-menu-right">
    <%if current_user%>
      <h3 class="username"><%=current_user.name.capitalize%></h3>
      <%=link_to user_path(current_user), class: 'link_to_user' do %>
        <i class="fa-solid fa-user"></i>
      <% end %>
    <%else%>
      <%=link_to 'Iniciar Sesión' , login_path, class:'navbar-login-btn'%>
    <%end%>
  </div>
</div>

<div class="responsive-navbar">
  <%=image_tag 'logo.png', class: 'logo-image'%>

  <div class="burger-menu" id="burger-menu">
    <span></span>
    <span></span>
    <span></span>
  </div>

  <div class="navbar-menu" id="navbar-menu">
    <%=link_to 'Inicio' , root_path, class: {active: current_page?(root_path)}%>
        <%=link_to 'Galería' , gallery_path, class: {active: current_page?(gallery_path)}%>
          <%=link_to 'Contacto' , contact_path, class: {active: current_page?(contact_path)}%>
            <%=link_to 'Sobre mi' , about_me_path, class: {active: current_page?(about_me_path)}%>
              <%=link_to 'Catálogo' , store_path, class: {active: current_page?(store_path)}%>
                <%=link_to 'Patrones' , patterns_path, class: {active: current_page?(patterns_path)}%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HiddenPetal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%=render 'marquees/marquee', last_marquee: @last_marquee%>
    <%=render 'layouts/navbar'%>
    <%=render 'layouts/messages'%>
    <%= yield %>

    <script src="https://code.iconify.design/2/2.2.0/iconify.min.js"></script>
  </body>
</html>

app/views/pages/_filters_bar.html.erb
<div class="filters">
  <%if params[:category].present?%>
    <p style="font-size:.9rem;font-style:italic;font-weight:700;" class="actual-category">Visualizando categoría: <%=params[:category]%></p>
  <%end%>
  <div class="filter-select-box">
    <div class="filter-select-box-title">
      <p class="categories-filter-title btn-primary">Categorías</p>
    </div>

     <div class="filter-select-box-title-responsive" id="filter-select-box-title-responsive" style="position:relative;width:100vw">
      <p class="categories-filter-title-responsive btn-primary" style="z-index=50;position:absolute;top:50%;right:5%;transform:translateY(-50%)">Categorías</p>
    </div>

    <div class="filter-select-box-options" id="filter-select-box-options">
      <%categories.each do |category|%>
        <%=link_to "#{category.name}", store_path(category: category.name), class: 'link'%>
      <%end%>
    </div>
  </div>
</div>

<div class="filter-select-box-options-offcanvas" id="filter-select-box-options-offcanvas">
  <div class="menu-close">
    <i class="fa-solid fa-circle-xmark"></i>
  </div>

  <div class="categories-links">
    <%categories.each do |category|%>
      <%=link_to "♥ #{category.name}", store_path(category: category.name), class: 'link'%>
    <%end%>
  </div>
</div>

app/views/pages/_home-slideshow-responsive.html.erb
<div data-controller="carousel" class="swiper-container" style="width:100vw; height:30vh;display:flex;align-items:center;justify-content:center;" data-carousel-options-value='
      {
        "pagination": {"el": ".swiper-pagination", "dynamicBullets": "true"},
        "autoplay": {"delay": "5000", "disableOnInteraction": "false"},
        "slidesPerView": "auto",
        "autoplay": {"delay": "4500", "disableOnInteraction": "true"}
      }'>
  <div class="swiper-wrapper" style="width:95%;height:250px;">
      <%products.each do |product|%>
        <div class="swiper-slide" style="width:250px;margin:0 15px;">
          <div class="product">
            <img src="<%=product.img%>" alt="" style="width:250px;height:250px;object-fit:cover;">
            <div class="product-details">
              <p class="name"><%=product.name%></p>
              <p class="price">$ <%=product.price%></p>
              <%=link_to 'Ver producto', producto_path(product), class: 'btn-primary'%>
            </div>
          </div>
        </div>
      <%end%>
  </div>
  <div class="swiper-pagination"></div>
</div>

app/views/pages/_home-slideshow.html.erb
<div data-controller="carousel" class="swiper-container" style="width:80vw; height:30vh" data-carousel-options-value='
      {
        "pagination": {"el": ".swiper-pagination", "dynamicBullets": "true"},
        "autoplay": {"delay": "5000", "disableOnInteraction": "false"},
        "slidesPerView": "auto",
        "autoplay": {"delay": "4500", "disableOnInteraction": "true"}
      }'>
  <div class="swiper-wrapper" style="width:90%;height:100%;">
      <%products.each do |product|%>
        <div class="swiper-slide" style="width:380px">
          <div class="product">
            <img src="<%=product.img%>" alt="" style="width:100%;height:100%;object-fit:cover;">
            <div class="product-details">
              <p class="name"><%=product.name%></p>
              <p class="price">$ <%=product.price%></p>
              <%=link_to 'Ver producto', producto_path(product), class: 'btn-primary'%>
            </div>
          </div>
        </div>
      <%end%>
  </div>
  <div class="swiper-pagination"></div>
</div>

app/views/pages/_product.html.erb
<%obj.each do |product|%>
  <div class="product-card">
    <div class="image-container">
      <div class="product-card-description">
        <%=link_to '', "producto/#{product.id}", class: 'product-link'%>
          <p class="description">
            Ir al producto
          </p>
      </div>
      <img src="<%=product.img%>" alt="">
    </div>
    <div class="product-text">
      <p class="product-card-name"><%=product.name%></p>
      <p class="product-card-price">$<%=product.price%></p>
    </div>
  </div>
<%end%>

app/views/pages/_section-one.html.erb
<section class="section-one">
  <div class="store-preview">
    <%@store_preview.each do |product|%>
      <div class="product-card">
        <div class="product-image">
          <%if product.image%>
            <img src="<%=product.img%>" alt="">
          <%else%>
            <p>no image</p>
          <%end%>
        </div>
        <div class="product-text">
          <p class="product-name"><%=product.name%></p>
          <p class="product-price">$<%=product.price%></p>
          <%=link_to 'Ver producto', "producto/#{product.id}", class: 'product-link'%>
        </div>
      </div>
    <%end%>
  </div>
  <div class="slider">
    <div class="slides">
      <%@store_preview.each.with_index do |product, index|%>
        <div class="slide-<%=index + 1%>">
          <div class="slide-content">
          <div class="slide-bg-dark"></div>
            <img src="<%=product.img%>" alt="">
            <div class="slide-text">
              <%=link_to product.name, "producto/#{product.id}"%>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/pages/_section-three.html.erb
<section class="section-three">
  <div class="section-three-container">
    <div class="image"></div>
    <div class="text-container">
      <div class="text">
        <%if @noticia%>
          <h1><%=@noticia.title%></h1>
          <small>Editado el <span><%=@noticia.updated_at.strftime("%d/%m a las %H:%M")%></span> por Mica</small>
          <p><%=@noticia.desc%></p>
        <%else%>
          <p>No hay noticias actualmente</p>
        <%end%>
      </div>
    </div>
  </div>
</section>

app/views/pages/_section-two.html.erb
<section class="section-two">
  <h1 class="section-two-heading">everything here is handmade</h1>
  <div class="section-two-content">
    <div class="one">
      <div class="text">
        <p>Hola! Soy Micaela🤎 Quiero contarte que Hidden Petal es un proyecto que siempre estuvo en mi corazón, 
        acá vas a poder encontrar prendas, muñecos, accesorios y objetos para el hogar 🤲🏻</p>
        <p>T O D O lo que veas en esta página es trabajo de artesanos! Muchas cosas están incluso hechas por mí 🥰</p>
        <p>Te invito a recorrer esta página web para conocer más sobre Hidden Petal y ser parte de quienes 
        eligen comprar productos artesanales, de calidad y hechos con mucho amor 💕</p>
      </div>
    </div>
    <div class="two">
      <div class="frases-header"><p>frase de la semana</p></div>
      <div class="frase">
        <p><%=@frase&.frase%></p>
      </div>
    </div>

    <div class="three">
      <div class="foto"></div>
    </div>
  </div>
</section>

app/views/pages/about.html.erb
<%=render 'section-two'%>
<%=render 'section-three'%>

app/views/pages/contact.html.erb
<div class="contact-container">
  <h3>Para compras POR MAYOR comunicarse por cualquiera de estos medios.</h3>
  <div class="content">
    <div class="left">
      <div class="contact-link">
        <div class="contact-icon">
          <span class="iconify" data-icon="akar-icons:instagram-fill"></span>
        </div>
        <p>@hiddenpetal_</p>
      </div>

      <div class="contact-link">
        <div class="contact-icon">
          <span class="iconify" data-icon="brandico:facebook"></span>
        </div>
        <p>Hidden Petal</p>
      </div>

      <div class="contact-link">
        <div class="contact-icon">
          <span class="iconify" data-icon="akar-icons:whatsapp-fill"></span>
        </div>
        <p>011 2390 8937</p>
      </div>

      <div class="contact-link">
        <div class="contact-icon">
          <span class="iconify" data-icon="entypo:email"></span>
        </div>
        <p>@hiddenpetal@outlook.com</p>
      </div>
    </div>

    <div class="right">
      <div class="image">
      
      </div>
    </div>
  </div>
</div>

app/views/pages/forbidden.html.erb
<div class="forbidden-container">
  <div class="forbidden-message">
    <h1>No está autorizado a acceder a esta ruta</h1>
  </div>
</div>

app/views/pages/gallery.html.erb
<div class="gallery-container">
  <h2 class="gallery-title">¡Estas reseñas fueron enviadas por ustedes! Gracias por tomarse el tiempo <3</h2>

  <div class="gallery-images">
    <%@reviews.each do |review|%>
      <div class="review">
        <div class="review-image">
          <img src="<%=review.image%>" alt="">

          <div class="review-content">
            <p><%=review.content%></p>
            <span>- <%=review.user_name%></span>
          </div>
        </div>
        <div class="review-product">
          <p><%=review.product_name%></p>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="home-banner">
    <div class="bigscreen">
      <div data-controller="carousel" class="swiper-container" style="width:100vw; height:30vh" data-carousel-options-value='
        {
          "pagination": {"el": ".swiper-pagination", "dynamicBullets": "true"},
          "navigation": {"nextEl": ".swiper-button-next", "prevEl": ".swiper-button-prev"},
          "autoplay": {"delay": "5000", "disableOnInteraction": "false"}
        }'>
          <div class="swiper-wrapper">
            <!-- Slides -->
            <%if !@home_banner_big.nil?%>
              <%@home_banner_big.images.each do |img|%>
                <div class="swiper-slide">
                  <img src="<%=img%>" alt="image" style="width:100vw;height:30vh;object-fit:cover;">
                </div>
              <%end%>
            <%end%>
          </div>
          <div class="swiper-pagination"></div>
      </div>
    </div>

    <div class="celular">
        <div data-controller="carousel" class="swiper-container celular" style="width:100vw; height:30vh" data-carousel-options-value='
          {
            "pagination": {"el": ".swiper-pagination", "dynamicBullets": "true"},
            "navigation": {"nextEl": ".swiper-button-next", "prevEl": ".swiper-button-prev"},
            "autoplay": {"delay": "5000", "disableOnInteraction": "false"}
          }'>
            <div class="swiper-wrapper">
              <!-- Slides -->
              <%if !@home_banner_phone.nil?%>
                <%@home_banner_phone.images.each do |img|%>
                  <div class="swiper-slide">
                    <img src="<%=img%>" alt="image" style="width:100vw;height:30vh;object-fit:cover;">
                  </div>
                <%end%>
              <%end%>
            </div>
            <div class="swiper-pagination"></div>
        </div>
    </div>
  </div>

  <h2 class="home-products-title">¡Nuevos productos en stock!</h2>
  <div class="home-products">
    <div class="home-products-big-screen">
      <%=render 'home-slideshow', products: @store_preview%>
    </div>
    <div class="home-products-responsive">
      <%=render 'home-slideshow-responsive', products: @store_preview%>
    </div>
  </div>

  <div class="categories-bg">
    <div class="home-categories">
      <%@home_categories.each do |category|%>
        <div class="category">
          <%=link_to store_path(:category => category.name), style: "text-decoration:none;color:black;", class:'category-link' do%>
            <div class="category-bg" style="background-image:url(<%=category.image%>)"></div>
            <h1><%=category.name%></h1>
          <%end%>
        </div>
      <%end%>

      <div class="category last-cat">
        <%=link_to store_path, style: "text-decoration:none;color:black;" do%>
          <h1>Ver todo</h1>
        <%end%>
      </div>
    </div>
  </div>
  <%=render 'layouts/footer'%>
</div>

app/views/pages/store.html.erb
<div class="tienda-container">
  <div class="tienda-heading">
    <div class="bg-black"></div>
    <h1>Bienvenido a la tienda</h1>
    <small>Descubrí todos los productos de Hidden Petal</small>
  </div>
  <%=render 'filters_bar', categories: @categories%>
  <div class="products-wrapper">
    <div class="productos-container">
      <%=render 'product', obj: @products%>
    </div>
  </div>
 
  <%= will_paginate @products, :previous_label => 'Anterior', :next_label => 'Siguiente' %>
</div>

app/views/pages/working.html.erb
<div class="working">
  <h1>Página en desarrollo</h1>
  <p>😁</p>
</div>